- name: Install packages
  ansible.builtin.yum:
    name:
      - postgresql
      - postgresql-server
      - postgresql-contrib
      - postgresql-libs
      - python3-psycopg2
    state: present

- name: Check if PostgreSQL is initialized
  ansible.builtin.stat:
    path: "/var/lib/pgsql/data/pg_hba.conf"
  register: postgres_data

- name: Initialize PostgreSQL
  ansible.builtin.shell: "postgresql-setup initdb"
  when: not postgres_data.stat.exists

- name: postgresql
  ansible.builtin.service:
    name: postgresql
    state: started
    enabled: yes

- name: "Create app database"
  postgresql_db:
    state: present
    name: "{{ db_name }}"
    become: yes
  become_user: postgres

- name: "Create db user"
  postgresql_user:
      state: present
      name: "{{ db_user }}"
      password: "{{ db_password }}"
      become: yes
      become_user: postgres

- name: "Grant db user access to app db"
  postgresql_privs:
      type: database
      database: "{{ db_name }}"
      roles: "{{ db_user }}"
      grant_option: no
      privs: all
      become: yes
      become_user: postgres

- name: "Allow md5 connection for the db user"
  postgresql_pg_hba:
      dest: "~/data/pg_hba.conf"
      contype: host
      databases: all
      method: md5
      users: "{{ db_user }}"
      create: true
      become: yes
  become_user: postgres
  notify: restart postgres

- name: "Add some dummy data to our database"
  become: true
  become_user: postgres
  shell: psql {{ db_name }} < /tmp/dump.sql

  handlers:
    - name: restart postgres
      service: name=postgresql state=restarted