- name: Install packages
  ansible.builtin.yum:
    name:
      - postgresql
      - postgresql15-server
      - postgresql-contrib
      - postgresql-libs
      - python3-psycopg2
    state: present

- name: Check if PostgreSQL is initialized
  ansible.builtin.stat:
    path: "/var/lib/pgsql/data/pg_hba.conf"
  register: postgres_data

- name: Initialize PostgreSQL
  ansible.builtin.shell: "postgresql-15-setup initdb"
  when: not postgres_data.stat.exists

- name: postgresql-15
  ansible.builtin.service:
    name: postgresql-15 
    state: started
    enabled: yes